export const productsData = [
  {
    id: '5ea9097e-c5f8-41de-b0a2-8e1a03df8b2d',
    title: 'Discovery',
    artist: 'Daft Punk',
    genre: 'electronic',
    tracks: [
      'One More Time',
      'Nightvision',
      'Superheroes',
      'High Life',
      'Something About Us',
      'Voyager',
      'Veridis Quo',
      'Short Circuit',
      'Face to Face',
      'Too Long',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'db267893-4258-4a6e-a350-db8862519de7',
    title: 'The Köln Concert',
    artist: 'Keith Jarrett',
    genre: 'jazz',
    tracks: [
      'Part I',
      'Part II A',
      'Part II B',
      'Part II C',
      'Part II D',
      'Part II E',
      'Part III A',
      'Part III B',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    deletedAt: '2024-06-01T00:00:00.000Z',
  },
  {
    id: 'f058a75d-7db1-4788-ac8f-ba674b26f23f',
    title: 'Exodus',
    artist: 'Bob Marley & The Wailers',
    genre: 'reggae',
    tracks: [
      'Natural Mystic',
      'So Much Things to Say',
      'Guiltiness',
      'The Heathen',
      'Exodus',
      'Jamming',
      'Waiting in Vain',
      'Turn Your Lights Down Low',
      'Three Little Birds',
      'One Love/People Get Ready',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    deletedAt: null,
  },
];
